# Generated by Django 5.2.7 on 2025-10-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('days', models.IntegerField(default=7)),
                ('meals_per_day', models.IntegerField(default=4)),
                ('target_kcal', models.IntegerField(default=2000)),
            ],
        ),
    ]
